services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  # nextjs-app:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - "3000:3000"

  rust-api:
    restart: unless-stopped
    depends_on:
      - cassandra
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      RUST_LOG: info
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  cassandra-data:
  pgdata:


  