/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/dash'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashIndexRouteImport } from './routes/dash.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DashCompanyIdIndexRouteImport } from './routes/dash.$companyId.index'
import { Route as DashCompanyIdChannelIdRouteImport } from './routes/dash.$companyId.$channelId'
import { Route as DashCompanyIdMembersRouteImport } from './routes/dash.$companyId.members'
import { Route as DashCompanyIdTokensRouteImport } from './routes/dash.$companyId.tokens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashCompanyIdIndexRoute = DashCompanyIdIndexRouteImport.update({
  id: '/$companyId/',
  path: '/$companyId/',
  getParentRoute: () => DashRoute,
} as any)
const DashCompanyIdChannelIdRoute = DashCompanyIdChannelIdRouteImport.update({
  id: '/$companyId/$channelId',
  path: '/$companyId/$channelId',
  getParentRoute: () => DashRoute,
} as any)
const DashCompanyIdMembersRoute = DashCompanyIdMembersRouteImport.update({
  id: '/$companyId/members',
  path: '/$companyId/members',
  getParentRoute: () => DashRoute,
} as any)
const DashCompanyIdTokensRoute = DashCompanyIdTokensRouteImport.update({
  id: '/$companyId/tokens',
  path: '/$companyId/tokens',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dash/': typeof DashIndexRoute
  '/dash/$companyId/$channelId': typeof DashCompanyIdChannelIdRoute
  '/dash/$companyId/members': typeof DashCompanyIdMembersRoute
  '/dash/$companyId/tokens': typeof DashCompanyIdTokensRoute
  '/dash/$companyId/': typeof DashCompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dash': typeof DashIndexRoute
  '/dash/$companyId/$channelId': typeof DashCompanyIdChannelIdRoute
  '/dash/$companyId/members': typeof DashCompanyIdMembersRoute
  '/dash/$companyId/tokens': typeof DashCompanyIdTokensRoute
  '/dash/$companyId': typeof DashCompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dash/': typeof DashIndexRoute
  '/dash/$companyId/$channelId': typeof DashCompanyIdChannelIdRoute
  '/dash/$companyId/members': typeof DashCompanyIdMembersRoute
  '/dash/$companyId/tokens': typeof DashCompanyIdTokensRoute
  '/dash/$companyId/': typeof DashCompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash'
    | '/signin'
    | '/signup'
    | '/invite/$token'
    | '/dash/'
    | '/dash/$companyId/$channelId'
    | '/dash/$companyId/members'
    | '/dash/$companyId/tokens'
    | '/dash/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/invite/$token'
    | '/dash'
    | '/dash/$companyId/$channelId'
    | '/dash/$companyId/members'
    | '/dash/$companyId/tokens'
    | '/dash/$companyId'
  id:
    | '__root__'
    | '/'
    | '/dash'
    | '/signin'
    | '/signup'
    | '/invite/$token'
    | '/dash/'
    | '/dash/$companyId/$channelId'
    | '/dash/$companyId/members'
    | '/dash/$companyId/tokens'
    | '/dash/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/$companyId/': {
      id: '/dash/$companyId/'
      path: '/$companyId'
      fullPath: '/dash/$companyId/'
      preLoaderRoute: typeof DashCompanyIdIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/$companyId/$channelId': {
      id: '/dash/$companyId/$channelId'
      path: '/$companyId/$channelId'
      fullPath: '/dash/$companyId/$channelId'
      preLoaderRoute: typeof DashCompanyIdChannelIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/$companyId/members': {
      id: '/dash/$companyId/members'
      path: '/$companyId/members'
      fullPath: '/dash/$companyId/members'
      preLoaderRoute: typeof DashCompanyIdMembersRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/$companyId/tokens': {
      id: '/dash/$companyId/tokens'
      path: '/$companyId/tokens'
      fullPath: '/dash/$companyId/tokens'
      preLoaderRoute: typeof DashCompanyIdTokensRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashIndexRoute: typeof DashIndexRoute
  DashCompanyIdChannelIdRoute: typeof DashCompanyIdChannelIdRoute
  DashCompanyIdMembersRoute: typeof DashCompanyIdMembersRoute
  DashCompanyIdTokensRoute: typeof DashCompanyIdTokensRoute
  DashCompanyIdIndexRoute: typeof DashCompanyIdIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashIndexRoute: DashIndexRoute,
  DashCompanyIdChannelIdRoute: DashCompanyIdChannelIdRoute,
  DashCompanyIdMembersRoute: DashCompanyIdMembersRoute,
  DashCompanyIdTokensRoute: DashCompanyIdTokensRoute,
  DashCompanyIdIndexRoute: DashCompanyIdIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
