[package]
name = "raterlog"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "=1.40.0", features = ["full"] }
serde = { version = "=1.0.210", features = ["derive"] }
serde_json = "=1.0.128"
dotenv = "=0.15.0"
tracing = "=0.1.40"
tracing-subscriber = "=0.3.18"
actix-web = "=4.9.0"
actix-http = "=3.9.0"
actix-rt = "=2.10.0"
actix-server = "=2.5.0"
bytestring = "=1.3.1"
scylla = "=0.13.1"
tokio-postgres = { version = "=0.7.12", features = ["with-chrono-0_4", "with-serde_json-1"] }
postgres-protocol = "=0.6.7"
postgres-types = "=0.2.8"
url = "=2.5.2"
chrono = { version = "=0.4.38", features = ["serde"] }
time = "=0.3.36"
actix-cors = "=0.7.0"
argon2 = "=0.5.3"
password-hash = "=0.5.0"
base64ct = "=1.6.0"
blake2 = "=0.10.6"
sha2 = "=0.10.8"
digest = "=0.10.7"
block-buffer = "=0.10.4"
crypto-common = "=0.1.6"
hmac = "=0.12.1"
md-5 = "=0.10.6"
sha1 = "=0.10.6"
rand = "=0.8.5"
regex = "=1.10.6"
reqwest = { version = "=0.11.27", default-features = false, features = ["json", "rustls-tls"] }
uuid = { version = "=1.10.0", default-features = false }
idna = "=0.5.0"
cc = "=1.1.31"
jobserver = "=0.1.32"
indexmap = "=2.2.6"
hashbrown = "=0.14.5"
unicode-segmentation = "=1.11.0"
